name: Publish Nightly Next

on:
  schedule:
    - cron: '0 9 * * *' # After zrender nightly published
  # committers can manually trigger with workflow_dispatch
  workflow_dispatch: {}
  repository_dispatch:
    types: publish-nightly-next

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'apache' }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: next

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
      - name: Setup and publish nightly
        run: |
          npm i
          npm i zrender@npm:zrender-nightly@next
          npm ls zrender
          npm run release
          npm run test
          npm run test:dts
          node build/prepareNightly.js --next
          npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
